// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A horror script generator AI agent supporting multiple languages.
 *
 * - generateHorrorScript - A function that handles the horror script generation process.
 * - GenerateHorrorScriptInput - The input type for the generateHorrorScript function.
 * - GenerateHorrorScriptOutput - The return type for the generateHorrorScript function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const MoodSchema = z.enum([
  'Psychological',
  'Supernatural',
  'Gore',
  'Thriller',
  'Paranormal Mystery',
]);

const LengthSchema = z.enum(['Short', 'Medium', 'Long']);

const LanguageSchema = z.enum(["Hindi", "English", "Spanish", "French"]).describe('The language for the output script.');

const GenerateHorrorScriptInputSchema = z.object({
  mood: MoodSchema.describe(
    'The mood of the horror script. Allowed values: Psychological, Supernatural, Gore, Thriller, Paranormal Mystery.'
  ),
  length: LengthSchema.describe(
    'The length of the horror script. Allowed values: Short, Medium, Long.'
  ),
  language: LanguageSchema, // Added language field
  words: z.coerce.number().int().min(50).max(2000).describe('The number of words in the script.'),
  referencePrompt: z.string().optional().describe('An optional reference prompt or story idea to guide the script generation.'),
});
export type GenerateHorrorScriptInput = z.infer<typeof GenerateHorrorScriptInputSchema>;

const GenerateHorrorScriptOutputSchema = z.object({
  script: z.string().describe('The generated horror script in the specified language.'),
});
export type GenerateHorrorScriptOutput = z.infer<typeof GenerateHorrorScriptOutputSchema>;

export async function generateHorrorScript(
  input: GenerateHorrorScriptInput
): Promise<GenerateHorrorScriptOutput> {
  return generateHorrorScriptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateHorrorScriptPrompt',
  input: {
    schema: GenerateHorrorScriptInputSchema, // Use the updated schema here
  },
  output: {
    schema: GenerateHorrorScriptOutputSchema, // Use the updated schema here
  },
  prompt: `You are a horror script writer specializing in cinematic writing styles.
  Please generate the following script in {{language}}.

  Write a horror script in {{language}} with the following characteristics:

  Mood: {{mood}}
  Length: {{length}}
  Words: {{words}}

  {{#if referencePrompt}}
  Use the following reference prompt/idea as inspiration:
  {{referencePrompt}}
  {{/if}}

  The story must follow a cinematic writing style with visual and sensory detail. Integrate story "hooks": gripping openers, cliffhangers, and twists. Focus on horror-specific themes (ghosts, rural legends, suspense, etc.). Include dialogues.
  `,
});

const generateHorrorScriptFlow = ai.defineFlow<
  typeof GenerateHorrorScriptInputSchema,
  typeof GenerateHorrorScriptOutputSchema
>(
  {
    name: 'generateHorrorScriptFlow',
    inputSchema: GenerateHorrorScriptInputSchema,
    outputSchema: GenerateHorrorScriptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
